name: maven-deploy
description: Run maven deploy lifecycle step
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SERVER_ID }}
inputs:
  SERVER_ID:
    description: Maven server id
    required: true